CREATE TABLE IF NOT EXISTS `comments`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `sku` VARCHAR(45) NOT NULL COMMENT '',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `description` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idx_name_sku` (`name` ASC, `sku` ASC)  COMMENT '',
  FULLTEXT INDEX `idx_desc` (`sku` ASC)  COMMENT '')
ENGINE = InnoDB;