CREATE TABLE IF NOT EXISTS `comments`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` TEXT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_title` (`title` ASC)  COMMENT '',
  FULLTEXT INDEX `idx_content` (`content` ASC)  COMMENT '')
ENGINE = InnoDB;